name: New Example
description: Add a new example for an existing design pattern.
title: "[Example]: "
labels: new example
body:
  - type: input
    id: example_name
    attributes:
      label: Example Name
      description: Provide a descriptive name for your example.
      placeholder: "e.g., Database Connection Manager."
  - type: input
    id: pattern_name
    attributes:
      label: Design Pattern Name
      description: Specify the design pattern to which this example belongs.
      placeholder: "e.g., Singleton, Factory, Observer."
  - type: textarea
    id: proposal
    attributes:
      label: Example Description
      description: Provide a detailed description of your example, including its purpose and how it aligns with the design pattern.
      placeholder: "Describe your example, its purpose, and how it implements the design pattern."
      
